subscription Recipes {
  recipes(order_by: { name: asc }) {
    id
    name
    description
    settings
    auto_apply
    created_at
    updated_at
    clips_aggregate {
      aggregate {
        count
      }
    }
  }
}

mutation InsertRecipe($name: String!, $description: String, $settings: jsonb!, $auto_apply: Boolean!) {
  insert_recipes_one(object: { name: $name, description: $description, settings: $settings, auto_apply: $auto_apply }) {
    id
  }
}

mutation UpdateRecipe($id: uuid!, $name: String, $description: String, $settings: jsonb, $auto_apply: Boolean) {
  update_recipes_by_pk(pk_columns: { id: $id }, _set: { name: $name, description: $description, settings: $settings, auto_apply: $auto_apply }) {
    id
  }
}

mutation DeleteRecipe($id: uuid!) {
  delete_recipes_by_pk(id: $id) {
    id
  }
}
